-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Goals"
(
    "Id" serial NOT NULL,
    "Title" character varying(50) NOT NULL,
    "Description" character varying(250) NOT NULL,
    "StartDate" date NOT NULL,
    "Relevancy" real NOT NULL,
    PRIMARY KEY ("Id")
    );

CREATE TABLE IF NOT EXISTS public."Tags"
(
    "Id" serial NOT NULL,
    "TagName" character varying(50) NOT NULL,
    "Color" integer NOT NULL,
    PRIMARY KEY ("Id")
    );

CREATE TABLE IF NOT EXISTS public."Notifications"
(
    "Id" serial NOT NULL,
    "NotificationType" character varying(50) NOT NULL,
    PRIMARY KEY ("Id")
    );

CREATE TABLE IF NOT EXISTS public."Goals_Notifications"
(
    "Goals_Id" serial NOT NULL,
    "Notifications_Id" serial NOT NULL
);

CREATE TABLE IF NOT EXISTS public."Goals_Tags"
(
    "Goals_Id" serial NOT NULL,
    "Tags_Id" serial NOT NULL
);

ALTER TABLE IF EXISTS public."Goals_Notifications"
    ADD FOREIGN KEY ("Goals_Id")
    REFERENCES public."Goals" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Goals_Notifications"
    ADD FOREIGN KEY ("Notifications_Id")
    REFERENCES public."Notifications" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Goals_Tags"
    ADD FOREIGN KEY ("Goals_Id")
    REFERENCES public."Goals" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Goals_Tags"
    ADD FOREIGN KEY ("Tags_Id")
    REFERENCES public."Tags" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION
    NOT VALID;

END;