-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."goals"
(
    "Id" integer NOT NULL DEFAULT nextval('"Goals_Id_seq"'::regclass),
    "Title" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "Description" character varying(250) COLLATE pg_catalog."default" NOT NULL,
    "StartDate" date NOT NULL,
    "Relevancy" real NOT NULL,
    "Pin" boolean NOT NULL,
    "Done" boolean NOT NULL,
    CONSTRAINT "Goals_pkey" PRIMARY KEY ("Id")
    );

CREATE TABLE IF NOT EXISTS public."goals_tags"
(
    "Goals_Id" integer NOT NULL DEFAULT nextval('"Goals_Tags_Goals_Id_seq"'::regclass),
    "Tags_Id" integer NOT NULL DEFAULT nextval('"Goals_Tags_Tags_Id_seq"'::regclass)
    );

CREATE TABLE IF NOT EXISTS public."tags"
(
    "Id" integer NOT NULL DEFAULT nextval('"Tags_Id_seq"'::regclass),
    "TagName" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "Color" integer NOT NULL,
    CONSTRAINT "Tags_pkey" PRIMARY KEY ("Id")
    );

ALTER TABLE IF EXISTS public.goals_tags
    ADD CONSTRAINT "Goals_Tags_Goals_Id_fkey" FOREIGN KEY ("Goals_Id")
    REFERENCES public.goals (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION
    NOT VALID;

END;